# Generated by Django 2.2.5 on 2019-12-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, unique=True)),
                ('course_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('hr_name', models.CharField(max_length=200)),
                ('hr_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hr_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_mobile', models.IntegerField()),
                ('trainer_doj', models.DateField(verbose_name='%d/%%m/%y')),
                ('trainer_email', models.CharField(max_length=200)),
                ('trainer_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('trainer_password', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=150, unique=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
            ],
        ),
    ]
