# Generated by Django 2.2.5 on 2019-12-04 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 4)),
        ),
    ]
