# Generated by Django 2.2.5 on 2019-12-04 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20191204_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_address', models.CharField(max_length=250)),
                ('user_mobile', models.IntegerField()),
                ('user_doj', models.DateTimeField(default=datetime.date(2019, 12, 4))),
                ('user_email', models.CharField(max_length=200)),
                ('user_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('user_payment', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_flag', models.IntegerField(default=0)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.CharField(max_length=250)),
                ('feedback_date', models.DateTimeField(default=datetime.date(2019, 12, 4))),
                ('feedback_comment', models.CharField(max_length=350, null=True)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Trainer')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.User')),
            ],
        ),
    ]
